# Generated by Django 4.0.6 on 2022-07-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('issuing_time', models.DateTimeField(verbose_name='Дата выдачи')),
                ('full_name_recipients', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks_id', models.IntegerField()),
                ('item', models.CharField(max_length=30, verbose_name='Название')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks_id', models.IntegerField()),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
        ),
    ]
