# Generated by Django 4.0.6 on 2022-08-01 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_column='Адрес', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('stocks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifo_lifo_app.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(db_column='Количество')),
                ('issuing_time', models.DateTimeField(db_column='Дата выдачи')),
                ('full_name_recipients', models.CharField(db_column='ФИО', max_length=50)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifo_lifo_app.donation')),
            ],
        ),
    ]
