# Generated by Django 4.0.6 on 2022-08-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
