# Generated by Django 4.0.6 on 2022-07-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stocks_id',
        ),
    ]
