# Generated by Django 4.0.6 on 2022-08-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0002_delete_donation_delete_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='order',
        ),
        migrations.RemoveField(
            model_name='requestthings',
            name='help_request',
        ),
        migrations.AddField(
            model_name='requestthings',
            name='help_request',
            field=models.ManyToManyField(to='fifo_lifo_app.helprequest'),
        ),
    ]
