# Generated by Django 4.0.6 on 2022-08-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0002_auto_20220801_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donate',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donate',
            name='full_name_recipients',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donate',
            name='issuing_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
