# Generated by Django 4.0.6 on 2022-07-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0002_remove_stock_stocks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='full_name_recipients',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
    ]
