# Generated by Django 4.0.6 on 2022-07-26 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0003_alter_donate_full_name_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='amount',
            field=models.IntegerField(db_column='Количество'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='donation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifo_lifo_app.donation'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='full_name_recipients',
            field=models.CharField(db_column='ФИО', max_length=50),
        ),
        migrations.AlterField(
            model_name='donate',
            name='issuing_time',
            field=models.DateTimeField(db_column='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(db_column='Количество'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='item',
            field=models.CharField(db_column='Название', max_length=30),
        ),
        migrations.AlterField(
            model_name='donation',
            name='stocks_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifo_lifo_app.stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='address',
            field=models.CharField(db_column='Адрес', max_length=100),
        ),
    ]
