# Generated by Django 4.0.6 on 2022-08-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0003_stock_name_alter_donate_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
    ]
