# Generated by Django 4.0.6 on 2022-07-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0004_alter_donate_amount_alter_donate_donation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donate',
            old_name='donation_id',
            new_name='donation',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='stocks_id',
            new_name='stocks',
        ),
    ]
