# Generated by Django 4.0.6 on 2022-08-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0004_remove_stock_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='address',
            new_name='name_stock',
        ),
    ]
