# Generated by Django 4.0.6 on 2022-09-01 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0004_helprequest_order_remove_requestthings_help_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='order',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='requestthings',
            name='name_thing',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='DonationThings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_thing', models.CharField(max_length=40)),
                ('donation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fifo_lifo_app.helprequest')),
            ],
        ),
    ]
