# Generated by Django 4.0.6 on 2022-08-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0005_rename_address_stock_name_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
