# Generated by Django 4.0.6 on 2022-09-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0005_donation_alter_helprequest_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='order',
        ),
        migrations.AddField(
            model_name='donation',
            name='number_donation',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='number_request',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
