# Generated by Django 4.0.6 on 2022-09-01 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0006_remove_donation_order_remove_helprequest_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationthings',
            name='name_thing',
        ),
        migrations.AddField(
            model_name='donationthings',
            name='name',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationthings',
            name='donation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fifo_lifo_app.donation'),
        ),
    ]
