# Generated by Django 4.0.6 on 2022-08-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0006_donation_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Stocks',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='stocks',
            new_name='stock',
        ),
        migrations.AlterField(
            model_name='donation',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
