# Generated by Django 4.0.6 on 2022-08-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0007_rename_stock_stocks_rename_stocks_donation_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='state',
            field=models.CharField(choices=[('available', 'available'), ('booked', 'booked'), ('requested', 'requested'), ('shipped', 'shipped')], max_length=20),
        ),
    ]
