# Generated by Django 4.0.6 on 2022-09-01 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0007_remove_donationthings_name_thing_donationthings_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='number_donation',
        ),
        migrations.RemoveField(
            model_name='donationthings',
            name='donation',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='number_request',
        ),
        migrations.RemoveField(
            model_name='requestthings',
            name='help_request',
        ),
        migrations.AddField(
            model_name='donation',
            name='full_name_donator',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationthings',
            name='number_donation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fifo_lifo_app.donation'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='full_name_petitioner',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestthings',
            name='number_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fifo_lifo_app.helprequest'),
        ),
    ]
