# Generated by Django 4.0.6 on 2022-08-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0008_alter_donation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='state',
            field=models.CharField(choices=[('available', 'available'), ('booked', 'booked'), ('requested', 'requested'), ('shipped', 'shipped')], default='available', max_length=20),
        ),
    ]
