# Generated by Django 4.0.6 on 2022-09-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0008_remove_donation_number_donation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='full_name_donator',
        ),
        migrations.RemoveField(
            model_name='donationthings',
            name='name',
        ),
        migrations.AddField(
            model_name='donation',
            name='full_name_petitioner',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationthings',
            name='name_thing',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationthings',
            name='number_request',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
