# Generated by Django 4.0.6 on 2022-09-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0009_remove_donation_full_name_donator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='full_name_petitioner',
        ),
        migrations.RemoveField(
            model_name='donationthings',
            name='number_request',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='full_name_petitioner',
        ),
        migrations.AddField(
            model_name='donation',
            name='full_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationthings',
            name='number',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='full_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestthings',
            name='number',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
