# Generated by Django 4.0.6 on 2022-08-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0009_alter_donation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(db_column='latitude'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='name',
            field=models.CharField(db_column='Что жертвуете?', max_length=30),
        ),
        migrations.AlterField(
            model_name='donation',
            name='stock',
            field=models.ForeignKey(db_column='Пункт выдачи', on_delete=django.db.models.deletion.CASCADE, to='fifo_lifo_app.stocks'),
        ),
    ]
