# Generated by Django 4.0.6 on 2022-08-08 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0010_alter_donation_amount_alter_donation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='donation',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifo_lifo_app.stocks'),
        ),
    ]
