# Generated by Django 4.0.6 on 2022-09-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0010_remove_donation_full_name_petitioner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationthings',
            name='number',
        ),
        migrations.RemoveField(
            model_name='requestthings',
            name='number',
        ),
    ]
