# Generated by Django 4.0.6 on 2022-08-08 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0011_alter_donation_amount_alter_donation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='full_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Ваше ФИО'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(verbose_name='Какое количество?'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Что желаете пожертвовать?'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifo_lifo_app.stocks', verbose_name='Выберите склад:'),
        ),
    ]
