# Generated by Django 4.0.6 on 2022-08-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0012_donation_full_name_alter_donation_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='full_name',
            new_name='full_name_donator',
        ),
    ]
