# Generated by Django 4.0.6 on 2022-09-01 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0012_remove_donationthings_number_donation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationthings',
            name='number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fifo_lifo_app.donation'),
        ),
    ]
