# Generated by Django 4.0.6 on 2022-08-13 09:21

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0013_rename_full_name_donation_full_name_donator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='donation',
        ),
        migrations.AddField(
            model_name='stocks',
            name='occupied_places',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='stocks',
            name='vacancies',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='state',
            field=models.CharField(choices=[('available', 'available'), ('booked', 'booked'), ('requested', 'requested'), ('shipped', 'shipped')], default='available', max_length=20, verbose_name='Stocks'),
        ),
        migrations.AddConstraint(
            model_name='stocks',
            constraint=models.CheckConstraint(check=models.Q(('occupied_places__lte', django.db.models.expressions.F('vacancies'))), name='occupied_places_gte'),
        ),
        migrations.DeleteModel(
            name='Donate',
        ),
    ]
