# Generated by Django 4.0.6 on 2022-09-01 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0013_donationthings_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationthings',
            name='number',
        ),
        migrations.RemoveField(
            model_name='requestthings',
            name='number',
        ),
        migrations.AddField(
            model_name='donationthings',
            name='number_donation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fifo_lifo_app.donation'),
        ),
        migrations.AddField(
            model_name='requestthings',
            name='number_help',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fifo_lifo_app.helprequest'),
        ),
    ]
