# Generated by Django 4.0.6 on 2022-08-13 09:24

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0014_remove_donate_donation_stocks_occupied_places_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stocks',
            name='occupied_places_gte',
        ),
        migrations.AddConstraint(
            model_name='stocks',
            constraint=models.CheckConstraint(check=models.Q(('vacancies__gte', django.db.models.expressions.F('occupied_places'))), name='occupied_places_gte'),
        ),
    ]
