# Generated by Django 4.0.6 on 2022-09-05 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0014_remove_donationthings_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='requestthings',
            name='number_help',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='full_name',
        ),
        migrations.AddField(
            model_name='donation',
            name='full_name_donator',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='full_name_petitioner',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DonationThings',
        ),
        migrations.DeleteModel(
            name='RequestThings',
        ),
        migrations.AddField(
            model_name='requestitem',
            name='request_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fifo_lifo_app.helprequest'),
        ),
        migrations.AddField(
            model_name='donationitem',
            name='donation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fifo_lifo_app.donation'),
        ),
    ]
