# Generated by Django 4.0.6 on 2022-08-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0014_remove_donate_donation_stocks_occupied_places_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stocks',
            name='occupied_places_gte',
        ),
    ]
