# Generated by Django 4.0.6 on 2022-08-16 06:39

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0015_remove_stocks_occupied_places_gte'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stocks',
            constraint=models.CheckConstraint(check=models.Q(('vacancies__gte', django.db.models.expressions.F('occupied_places'))), name='occupied_places_gte'),
        ),
    ]
