# Generated by Django 4.0.6 on 2022-09-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0016_completedrequest_helprequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationitem',
            old_name='donation_id',
            new_name='donation',
        ),
        migrations.RenameField(
            model_name='requestitem',
            old_name='request_id',
            new_name='request',
        ),
        migrations.AddField(
            model_name='donationitem',
            name='status',
            field=models.CharField(choices=[('Free', 'Free'), ('Issued', 'Issued')], default='Free', max_length=15),
        ),
    ]
