# Generated by Django 4.0.6 on 2022-09-11 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0019_stocks_alter_donationitem_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='stock_id',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='helprequest',
            old_name='stock_id',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='full_name_donator',
        ),
    ]
