# Generated by Django 4.0.6 on 2022-09-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0020_rename_stock_id_donation_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
