# Generated by Django 4.0.6 on 2022-09-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0021_donation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='full_name_petitioner',
        ),
    ]
