# Generated by Django 4.0.6 on 2022-09-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0022_remove_donation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='name_stock',
            field=models.CharField(max_length=30),
        ),
    ]
