# Generated by Django 4.0.6 on 2022-09-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0023_donation_amount_alter_stocks_name_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
