# Generated by Django 4.0.6 on 2022-09-12 09:45

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0024_helprequest_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='amount',
        ),
        migrations.AddField(
            model_name='stocks',
            name='occupied_places',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='stocks',
            name='vacancies',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='stocks',
            constraint=models.CheckConstraint(check=models.Q(('vacancies__gte', django.db.models.expressions.F('occupied_places'))), name='occupied_places_gte'),
        ),
    ]
