# Generated by Django 4.0.6 on 2022-09-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0025_remove_donation_amount_remove_helprequest_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='stock',
        ),
    ]
