# Generated by Django 4.0.6 on 2022-09-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0026_remove_donation_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='stock',
        ),
    ]
