# Generated by Django 4.0.6 on 2022-09-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0028_donationitem_stock_requestitem_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
