# Generated by Django 4.0.6 on 2022-09-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0029_stocks_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='state',
        ),
    ]
