# Generated by Django 4.0.6 on 2022-09-24 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifo_lifo_app', '0030_remove_stocks_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationitem',
            name='category',
            field=models.CharField(choices=[('Верхняя одежда', 'Верхняя одежда'), ('Нижнее бельё', 'Нижнее бельё'), ('Еда', 'Еда')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestitem',
            name='category',
            field=models.CharField(choices=[('Верхняя одежда', 'Верхняя одежда'), ('Нижнее бельё', 'Нижнее бельё'), ('Еда', 'Еда')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationitem',
            name='name_item',
            field=models.CharField(max_length=50, verbose_name='Название вещи'),
        ),
        migrations.AlterField(
            model_name='donationitem',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fifo_lifo_app.stocks', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='name_item',
            field=models.CharField(max_length=50, verbose_name='Название вещи'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fifo_lifo_app.stocks', verbose_name='Склад'),
        ),
    ]
